env:
  global:
  - secure: 1yhgp3baJXVR4z+0UWpIHl4zPU1xFmJvLaX4oKuDLfdOfBn0gFpELOGKwmGGo/vel6a3PdxBU2nVTKNbUsVpctcsmG5JdzwpbMpfn3hlirxdpLRuMzWUBrlmdcwHKpOnnW3G5kqoh4JuQNjmlUOMqvuhHxQL8uxVy12o3pFa/VD9IIwPj4M3fV46gL8Gc6Oc2HVOrW8hmn0iEgUepgrZRHjAhSWrHLMOUVv42imYBjAbIBqt2Bh7E61IrOytiyJjK1wHSupuGrLUZ72vz59qX9so1ZVp7DxgTsXKYDF+zq8TS/hNVWUTaWhHtdFJV4kIhTdi3s51DXzzGSxnkTcLuwFZ5Mhe0kLojgfK4EhcoM856PDP97aKDaemaMWwtvsTEMzJaVAlmUaFAaFqZNdtqi7hZ9S14rLGRodMyno2ErbOSMhjQeFGXJfTQiGMNibFmj7RK83teEZoifpY3kRMfXdhdGpv3rHBy/51oKDDyVJzEXX6FrSYm2H6xLLy4+l+u23ADijFY62gt6stExpICLKppeP4USK12j+2IFnPRIa0wgDgm5ctlL5DWP3wDbDLgC8gMuzHL9x9rxI3dOfkVg6xrAoQa8kIFzd0Gpl725t8jD2naLQqMD/KzioffusuW1PFo6y4SZJRtnA+YCrWHnKH0wHz9oUGuX2lj8RzvXo=
  - secure: 1sZkkwso0pyZ3S+VsRzx0ecs6GICdw4UoFLmj9XBRYl8xbFWOBFrjHMmrfMDYKbvcY2deYDiY4tXKT1tJiXV0us8b2pFl/pGxs8taQQDIiOjGGzX4EMZ4XwFJHgUwc4teitarC3p51lt7VYndCNrqJIxA1TejCeV6GILxGaRMbBTGQz3WM2zJWGUY5tRmMVZcQcSuUat4uDQbAGcPvPkMTVRNp3iYmZ4iAyK6ptLdKYl0U9yvJBS6tsLPThUQ3YNnFFrhlxkzRRhbmVgOwrK0KdHZfap4KhrYbILYSFHVwFKHkLelt3ZlErs4Y5CkG0K/mVB8PUmXCWeWTFTOz+IuQgrQoaYC6Aj1LH3vnQ5xnesDwGCuuuoiDvoNM166Racz+gDXoTAtwA8YwPrCZycgZvtWc+X0ADs5xGYOtM31NBzf2fpmYKcrPO9Nx+96LwIht1OevcSfIE8dN5iRVE1ylP5K+35zvAbEaRJelWwq0IkjONp2/SKFxlFnqcWQ8U4786E2njETXzSWdWYjan5y9FzVBoXbkBMppDvDeD9uqbh5dE3e1WBCC+IxjCQX7c32PcK6z5SgQQ9/cAI6mpMWyTTBSV50FsS6UyLDf6Dn9YcX/uV6253DZkFH6V/woqCMJRsUDYJabYdNOgwY8+9uzvpp6hpRpKpFj0WEk89PN8=

language: objective-c
osx_image: xcode7.3

install:
  - bundle install
  - carthage bootstrap --platform iOS
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail
  - xcodebuild build test -scheme ZMTesting-ios -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' | tee >build.log >(xcpretty -s)
  - bundle exec danger

after_failure:
  - tail -n 500 build.log
