env:
  global:
    - secure: DUTI6xnk6emxAGtabSBfFH5QO6jxkRgjCWZp6fnXGrT125ZJ1Gdmf7+O9Gm/qfv9g2zUwjAnptgXUPvPT3xkdB256Ev7eLok9yTwErRd4vubbmxxu7+EqavYg1kQtdb6UStZ5c1Yz/S2mlqOxG5KMQxom80WU9Cfdq096q8hfeJ25hsNdoKBs1EN4Dyb8VxDdTRBHbADE8prqEDtNEprLEYBKzNkH9EbvR/1sPpZ6tsWFKG5mLNifaV/BDfogoFhsgex5EAibpUhXgC4L9zsJMk0Xh8iUOXNkxp7dsOxMeazEtfnUxB26nXUaH2aSopnahmznEtmsKWxLrUheKVKX8rms5fAWTvC8O7p5KYmijzckWGsLK02xRa2lFd71Muw73ZTHL3fLwRJKF7JuU1Aw9bWcVBVjh6rRVaXJloyvJ5rlqvlCWLbUmAJp3QeBJC8MYDenT2G0RIfGEAitNI91IleJrRkX9jmgdzTwa0q+37imIk/H0F4joG4RxXYIx/OU7a95cYvR2pZ9I7jmaRYMlK9jR9huykoP4J2HdsKvkIZhvaIc/wh37B2Pe+tm42vZtcpu3Axym078T5oBs2NDrBYKX0QEpG+eFNA7nshpcPkKvSh2BJN/GFEPgbuSbuzFPYUTmhGOEsM7g1vIsds+rb3zs5/wf48tTiBhPBYh00=
    - secure: mXarvuZYNFuY0Z/TqYPENoPWpGGU3fIn3rUokx7D05ue3t9hSA5v4RphMvaB9QE9IJaPb3CARvm243bvfYg3Bg66/XPklrkCB2zpMRwdrUOfUkYfymBwhB/hFX7aIj09WKV+NSW2V7FfiYC7WB7OglvYP+93iIaCnn/9KxADPz+kblPhn0uBCYpRcZiMdP7rQNBDJMPCFUxl/AlkvydgDCInsZNzfDUoNCxRsO91tW7NpIIWStM3tjx51Sl76XQAyNBTD6rN9EXIbVtfadapXA2VrV0lqUUxVMyr903huxbEoIEF+mUbdH1kJBnM5ZZeNCDvRNI6BMQnErK9SrHQbHfB3pipEGwGATOvyq9sqXx+PplwGgt3F4/1J3LICsoHVYMQXBhKmLkkovjggAHMtl0afTBGW5rujTCzI2ljzIEEKcmXjR2QKF0Jk92JUKSGJUWtW91t6Ilw6l9Hjvg6KYn/Ihl6ro78EhsEd4jGGFEQnZnoegVEwvhXM1LZ46cYZcv1VyuCyyrchyCvMu6msTBxGeFIXw5sI3JpTxJ7omkahLx/yVnUEpQjPM4e3Cs8X/+wB3JNApvMujk2+umSQ11fea0CgaNjCFJY26PnaQvVURX7Lz2vp08kWNEU/iXfDhysW/V4W92D4WlNFs1zzglyHzN/OND+qwOD8Cx2rLI=

language: ruby
cache: bundler
rvm: 2.0.0

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - develop
    - master

install:
  - bundle install
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - bundle exec danger
